### ISSUE TITLE
undefined method `note' for nil:NilClass

### ISSUE THREAD

**Issue by joric** [jimm/midilib#13]
I'm getting this (test_tottoro.bat, test_tottoro.sh, ruby 2.7, both linux and windows):

```ruby
chan_settings: ["d", "me", "p", "m", "m", "m", "me", "p", "mew"]
track , num_tracks 7, index 0
track #<MIDI::Track:0x000000000682f978>, num_tracks 7, index 1
...
mixing lchan:8 into 2
--- render into text ---
Traceback (most recent call last):                                                 
        7: from autosiril.rb:905:in `<main>'                                       
        6: from autosiril.rb:905:in `times'                                        
        5: from autosiril.rb:913:in `block in <main>'                              
        4: from autosiril.rb:913:in `map'                                          
        3: from autosiril.rb:914:in `block (2 levels) in <main>'                   
        2: from autosiril.rb:914:in `!='                                           
        1: from autosiril.rb:914:in `=='                                           
autosiril.rb:416:in `<=>': undefined method `note' for nil:NilClass (NoMethodError)
```
How to fix?

**Comment by joric** [comment]
Oops wrong repo, that's supposed for https://github.com/oisee/autosiril/
